//! Host-only (build-time) dequantization codegen for the Pulse protocol.
//!
//! Reads the `(decentraland.common.quantized)` field option (`{min, max, bits}`) straight from
//! the proto descriptor emitted by `build.rs` and generates a `{field}_dequantized()` accessor
//! for every pulse message field that carries it. This keeps the `.proto` the single source of
//! truth for the quantization ABI — the exact constants the C# server bakes via
//! `protoc-gen-bitwise` — instead of hand-transcribing them on the client side, where a silent
//! drift would decode to wrong positions with no compile error.
//!
//! Not a runtime dependency: the emitted file is plain const arithmetic, `include!`d into the
//! `pulse` proto module.

use std::fmt::Write as _;

use prost_reflect::{DescriptorPool, DynamicMessage, Value};

pub fn generate(descriptor_bytes: &[u8], out_path: &std::path::Path) {
    let pool = DescriptorPool::decode(descriptor_bytes).expect("decode descriptor");
    let quant = pool
        .get_extension_by_name("decentraland.common.quantized")
        .expect("quantized extension missing from descriptor");
    let quant_power = pool
        .get_extension_by_name("decentraland.common.quantized_power")
        .expect("quantized_power extension missing from descriptor");

    let mut out = String::new();
    out.push_str(
        "// @generated by build_quant.rs from the (decentraland.common.quantized[_power]) proto options. DO NOT EDIT.\n\n",
    );
    // Inverse of the server's Quantize.Encode: an encoded integer in [0, 2^bits - 1] maps back
    // onto the float range [min, max].
    out.push_str(
        "#[inline]\n\
         fn dequantize(encoded: u32, min: f32, max: f32, bits: u32) -> f32 {\n    \
         let levels = ((1u32 << bits) - 1) as f32;\n    \
         min + (encoded as f32 / levels) * (max - min)\n\
         }\n\n",
    );
    // Inverse of the server's Quantize.EncodePower: an (bits-1)-bit linear unorm magnitude `u` in
    // the high bits plus a sign in the LSB, reconstructed as `sign * max * u^pow`.
    // Zero (code 0) decodes to exactly 0.
    out.push_str(
        "#[inline]\n\
         fn dequantize_power(encoded: u32, max: f32, pow: f32, bits: u32) -> f32 {\n    \
         let mag_steps = ((1u32 << (bits - 1)) - 1) as f32;\n    \
         let u = (encoded >> 1) as f32 / mag_steps;\n    \
         let magnitude = max * u.powf(pow);\n    \
         if encoded & 1 != 0 { -magnitude } else { magnitude }\n\
         }\n\n",
    );

    for msg in pool.all_messages() {
        if msg.package_name() != "decentraland.pulse" {
            continue;
        }

        let mut accessors = String::new();
        for field in msg.fields() {
            let opts = field.options();
            let name = field.name();

            if opts.has_extension(&quant) {
                let value = opts.get_extension(&quant);
                let q = value
                    .as_message()
                    .expect("quantized option must be a message");
                let min = get_f32(q, "min");
                let max = get_f32(q, "max");
                let bits = get_u32(q, "bits");

                writeln!(
                    accessors,
                    "    /// Dequantized `{name}` ({min}..={max}, {bits} bits); `None` when absent from the delta.\n    \
                     pub fn {name}_dequantized(&self) -> Option<f32> {{\n        \
                     self.{name}.map(|v| dequantize(v, {min}f32, {max}f32, {bits}))\n    \
                     }}",
                )
                .unwrap();
            } else if opts.has_extension(&quant_power) {
                let value = opts.get_extension(&quant_power);
                let q = value
                    .as_message()
                    .expect("quantized_power option must be a message");
                let max = get_f32(q, "max");
                let pow = get_f32(q, "pow");
                let bits = get_u32(q, "bits");

                writeln!(
                    accessors,
                    "    /// Dequantized `{name}` (\u{00b1}{max}, power-law pow {pow}, {bits} bits); `None` when absent from the delta.\n    \
                     pub fn {name}_dequantized(&self) -> Option<f32> {{\n        \
                     self.{name}.map(|v| dequantize_power(v, {max}f32, {pow}f32, {bits}))\n    \
                     }}",
                )
                .unwrap();
            }
        }

        if accessors.is_empty() {
            continue;
        }

        writeln!(out, "impl {} {{\n{accessors}\n}}\n", msg.name()).unwrap();
    }

    std::fs::write(out_path, out).expect("write pulse_quant.rs");
}

fn get_f32(message: &DynamicMessage, field: &str) -> f32 {
    match message.get_field_by_name(field).as_deref() {
        Some(Value::F32(v)) => *v,
        other => panic!("quantized.{field} expected f32, got {other:?}"),
    }
}

fn get_u32(message: &DynamicMessage, field: &str) -> u32 {
    match message.get_field_by_name(field).as_deref() {
        Some(Value::U32(v)) => *v,
        other => panic!("quantized.{field} expected u32, got {other:?}"),
    }
}
