// Import the wasm-bindgen generated JS glue code and Rust functions
import init, {
    wasm_run,
} from './pkg/webgpu_build.js';

const initButton = document.getElementById('initButton');

async function run() {
    // Path to the _bg.wasm file generated by wasm-pack
    const wasmUrl = './pkg/webgpu_build_bg.wasm';
    const response = await fetch(wasmUrl);
    if (!response.ok) throw new Error(`Failed to fetch Wasm: ${response.statusText}`);
    let wasmBytes = await response.arrayBuffer();

    await init(wasmBytes);

    initButton.onclick = () => {
        wasm_run();
        console.log("exited");
    };
}

run().catch(error => {
    console.error("[Main JS] Top level error:", error);
});
