#!/bin/sh

cp ../target/release/decentra-bevy BevyExplorer.AppDir/usr/bin
cp ../assets BevyExplorer.AppDir/usr/bin -r

wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
wget https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage

./linuxdeploy-x86_64.AppImage --appdir BevyExplorer.AppDir --output appimage --create-desktop-file --executable=usr/bin/decentra-bevy --icon-file=decentra-bevy.png
