[package]
name = "user_input"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
common = { workspace = true }
input_manager = { workspace = true }
scene_runner = { workspace = true }
dcl_component = { workspace = true }
tween = { workspace = true }
console = { workspace = true }

bevy = { workspace = true }
bevy_console = { workspace = true }
rapier3d-f64 = { workspace = true }
clap = { workspace = true }
