// Hosts the engine in a same-origin iframe (served by the Vite middleware under
// /engine/) and hands its window to the EngineRpc once loaded. Sits behind the
// React UI overlay; becomes visible when the login overlay unmounts.

import { useEffect, useRef } from 'react'
import type { EngineRpc } from '../../engine/engineRpc'
import { PAGE_DIR } from '../../lib/publicUrl'

const REALM = 'https://realm-provider-ea.decentraland.org/main'

// The engine iframe MUST stay same-origin with this page — BroadcastChannel and direct
// iframe.contentWindow access don't cross origins — so it can NEVER live on the asset CDN
// (in prod, Vite's base/PUBLIC_URL is cdn.decentraland.org/<pkg>/<version>/ while the page is
// served at e.g. decentraland.zone/bevy-web, which mirrors the same package tree). Resolve
// engine URLs against PAGE_DIR (the page treated as a directory), never against the base.

// Our super-user bridge scene. It relays the scene-loading stream + player-ready over
// BroadcastChannel and renders no UI.
//   • PROD (built app): the EXPORTED static bundle shipped in this package at
//     `bridge-scene/static` (generated by `cd bridge-scene && npm run bundle`), served
//     same-origin beside the page.
//   • DEV default: the LIVE preview realm from `sdk-commands start` on :8100 — fast iteration
//     (the scene hot-reloads). Run it: `cd bridge-scene && npx sdk-commands start --port 8100`.
//   • `?bundled=1` (dev): opt into the exported bundle — exactly what ships.
const SYSTEM_SCENE =
  import.meta.env.PROD || new URLSearchParams(location.search).has('bundled')
    ? new URL('bridge-scene/static/BevyExplorerUI', PAGE_DIR).href
    : 'http://localhost:8100'

// Engine/scene params on the page URL ride through to the iframe for parity with the plain
// engine page (?position, ?realm, ?portables, ?preview, …). The engine hands its whole query
// string to scenes as SceneParams, so unknown keys are forwarded verbatim too. App-level params
// stay out, and this host owns initialRealm (override with ?realm), systemScene (overridable),
// hideLoader and manualParams — the deferred-launch flow depends on the last two.
// Never forwarded: the app's own flags, plus the two this host always sets itself below.
const EXCLUDED_PARAMS = new Set([
  'mock', 'showcase', 'gate', 'nogate', 'simerror', 'bundled', 'fps', 'previousLogin',
  'initialRealm', 'manualParams'
])
const engineQuery = ((): URLSearchParams => {
  const q = new URLSearchParams()
  for (const [k, v] of new URLSearchParams(location.search)) {
    if (!EXCLUDED_PARAMS.has(k)) q.set(k, v)
  }
  q.set('initialRealm', q.get('realm') ?? REALM)
  q.delete('realm')
  if (!q.has('systemScene')) q.set('systemScene', SYSTEM_SCENE)
  if (!q.has('position')) q.set('position', '0,0')
  // hideLoader=1 suppresses the engine's built-in loading UI — React renders the only loader.
  // manualParams=1 → the engine compiles the WASM + warms the GPU cache but does NOT auto-run the
  // bevy app, so no realm scene loads. The host launches it (engine_run) at the user's chosen
  // destination once they pick in the post-jump-in Places picker — avoiding a wasted Genesis load.
  q.set('hideLoader', '1')
  q.set('manualParams', '1')
  return q
})()

// Trailing slash matters: the engine derives its service-worker scope + worker
// paths from location.pathname, so it must boot at /engine/ not /engine/index.html.
const ENGINE_SRC = `${new URL('engine/', PAGE_DIR).href}?${engineQuery.toString()}`

export function EngineHost({ rpc }: { rpc: EngineRpc }): React.JSX.Element {
  const ref = useRef<HTMLIFrameElement>(null)

  useEffect(() => {
    const iframe = ref.current
    if (!iframe) return
    const attach = (): void => rpc.setWindow(iframe.contentWindow)
    iframe.addEventListener('load', attach)
    if (iframe.contentWindow) attach()
    return () => {
      iframe.removeEventListener('load', attach)
      rpc.setWindow(null)
    }
  }, [rpc])

  return (
    <iframe
      ref={ref}
      src={ENGINE_SRC}
      title="Decentraland engine"
      allow="autoplay; fullscreen; xr-spatial-tracking; microphone; clipboard-write"
      style={{
        position: 'fixed',
        inset: 0,
        width: '100%',
        height: '100%',
        border: 'none',
        zIndex: 0
      }}
    />
  )
}
